### ISSUE TITLE
Focus is incorrect for new scenario

### ISSUE THREAD

**Issue by gauriwahi** [biltzerpos/TBB#2]
During the Alpha test, we noticed that the focus is incorrect when trying to create a new scenario. Instead of going into the text field, the focus goes directly to the "Ok" button.

##Expected Result##
Goes to the text field for Cell

##Actual result##
Focus is on OK

**Comment by biltzerpos** [comment]
@yassinmmoussa  Hi Yassin, please look into it

**Comment by yassinmmoussa** [comment]
Hey Gauri, was this on Windows or Mac? And were you using Jaws, VoiceOver or NVDA?

**Comment by gauriwahi** [comment]
We were using Windows, and NVDA

**Comment by yassinmmoussa** [comment]
Hey Gauri, I haven't been able to reproduce the problem at all, however this is one of the older bugs we had encountered that we had fixed a while ago.  While the fix is indeed implemented in the code you ran the alpha test on, can I ask you to try reproducing the code on my fork?https://github.com/yassinmmoussa/TBB.git
If that's a problem I can simply look at it during tomorrow's meeting

**Comment by gauriwahi** [comment]
Hey, 
I think Runa would have a better idea of how we came to the problem since she was playing around it. We can ask her tomorrow during the meeting!
