### ISSUE TITLE
Set Voice takes in any number

### ISSUE THREAD

**Issue by gauriwahi** [biltzerpos/TBB#28]
1. Run Authoring App
2. Click on New Scenario
3. Cell : 1, Button: 2, Title: Test 3
4. Click on New Item
5. Select Option - Set Voice
6. Type in 1
7. Repeat steps 4 and 5
8. Type in 2
9. Repeat step 7
10. Type in 3
11. Repeat step 7
12. Type in 45

Expected Behaviour: User has options to choose from either radio buttons or drop down combo-box. 
Actual Behaviour: User is able to enter any amount, and if it is in the range from 1-3 it will be displayed as either a male or female voice. Otherwise the scenario says "TTS Voice to use: [blank]" where [blank] contains no information but it is seen.

**Comment by yassinmmoussa** [comment]
@biltzerpos Since we've removed multiple voice functionality (as in mbrola) should I just remove this as an option?

**Comment by yassinmmoussa** [comment]
Done

**Comment by biltzerpos** [comment]
This still needs some work. It is not clear what values are appropriate for voices. I believe that that once the user selects "Set Voice" they should get either a combo box or a set of radio buttons that also contain descriptions of each voice, i.e. Male, Female etc.

**Comment by gauriwahi** [comment]
This still needs to be done!

**Comment by katedmc** [comment]
I have changed the Set Voice item to be a combo box. The voice labels are listed similarly to how they are displayed on the left window pane, but I placed the numbers first for parsing. I also updated the JOptionPane text to reflect the selection instead of entering a number.
I'm not sure what the descriptions for the voices should be, and if this should include an accessible description.

**Comment by mbaljko** [comment]
in progress - discussed and reviewed at meeting 29 May 2018

**Comment by biltzerpos** [comment]
Fixed by Dyllan
